<?php

namespace App;

return [
  'SEGURO CASHBANK',
  'Lote PREMIUM',
  'Lote INFERIOR',
  'Lote PRIME',
  'Prêmio Único',
  'Acesso Vitalício',
  'Selecionado',
  'Taxa de Anuidade',
  'LOTE BÁSICO',
  'LOTE PLUS',
  'LOTE PREMIUM',
  'Brinde Exclusivo',
  'Última Unidade',
  "LOTE BÁSICO",
  "LOTE PREMIUM",
  "Finalizar Pagamento",
  "Carteira DIGIBANK",
  "Cartão Físico",
  "Carteira NEO",
  "Tarifa Única",
  "Saque Imediato",
  "Prêmio Grátis",
  "Taxa Transacional",
  "Pagamento",
  "Ultra Cleaner",
  "Lote Prime 7 Caixas",
  "Lote Básico 4 Caixas",
  "Pacote Exclusivo 16 caixas Iphones computadores e muito mais 1Un disponíveis",
  "Lote Premium 12 Caixas",
  "OFERTA APLICADA PONTO",
  "DESCONTO APLICADO",
  "OFERTA APLICADA",
  "Oferta Especial",
  "Garantia Estendida 2 Anos",
  "Doação",
  "Finalize seu pagamento",
  "Pagamento",
  "Ovo de páscoa",
  "Tarifa Transacional",
  "QUEIMA DE ESTOQUE 2",
  "rastreio",
  "OFERTA APLICADA",
  "Oferta 2 Pacotes",
  "Taxa de Inscrio",
  "Receba em at 2h",
  "Voc ganhou um super desconto",
  "Taxa de Emisso de Nota Fiscal",
  "Frete Recalculado",
  "Tarfa nica (x1)",
  "LOTE PLUS (x1)",
  "LOTE BSICO (x1)",
  "ÚLTIMO DIA PARA RESGATAR O SEU KIT",
  "Cor Selecionada Grafite",
  "Promoção Exclusiva",
  "ÚLTIMA UNIDADE",
  "LIBERAÇÃO DE PRODUTO CORREIOS",
  "Desbloqueio de Conta",
  "Com Carinho",
  "Super Oferta de fim de Estoque",
  "Selecionado",
  "Complete aqui",
  "Cartão",
];